apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-backend
  template:
    metadata:
      labels:
        app: trading-backend
    spec:
      containers:
      - name: backend
        image: 975050024946.dkr.ecr.eu-west-2.amazonaws.com/trading-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: AWS_BUCKET_NAME
          value: "tradinggame-capstone"