{
 "title": "Total request",
 "description": "sum(http_requests_total)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "description": "process_cpu_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "bargauge",
   "description": "process_resident_memory_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Average Response Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) \n/\nsum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "description": "Request Rate (req/sec)\nsum(rate(http_requests_total[5m]))",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes > 200000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total[5m])) == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "table",
   "description": "process_cpu_seconds_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}